import { Cart } from './cart/cart';
import { Follows } from './follow/follow';
import { Comment, Comments } from './comment/comment';
import { AuthPayload, Member } from './member/member';
import { Order, Orders } from './order/order';
import { Payment } from './payment/payment';
import { Pet, Pets } from './pet/pet';
import { Product, Products } from './product/product';

export interface T {
	getAllProductsByAdmin?: Products;
	getAllPetsByAdmin?: Pets;
	getAllOrdersByAdmin?: Orders;
	getAllMembersByAdmin?: { list: Member[]; metaCounter: { total: number }[] };
	updateProductByAdmin?: Product;
	updatePetByAdmin?: Pet;
	updateOrderStatusByAdmin?: Order;
	updateMemberByAdmin?: Member;
	signup?: Member;
	login?: AuthPayload;
	getMember?: Member;
	getMemberFollowers?: Follows;
	getMemberFollowings?: Follows;
	updateMember?: Member;
	getProduct?: Product;
	getProducts?: Products;
	getMyProducts?: Products;
	createProduct?: Product;
	updateProduct?: Product;
	removeProduct?: Product;
	getPets?: Pets;
	getPet?: Pet;
	getMyPets?: Pets;
	getFavoritePets?: Pets;
	getVisitedPets?: Pets;
	getComments?: Comments;
	createComment?: Comment;
	updateComment?: Comment;
	likeTargetPet?: Pet;
	createPet?: Pet;
	updatePet?: Pet;
	getMyCart?: Cart;
	addToCart?: Cart;
	updateCartItem?: Cart;
	removeCartItem?: Cart;
	clearCart?: Cart;
	createOrder?: Order;
	getMyOrders?: Orders;
	getOrder?: Order;
	cancelOrder?: Order;
	createPayment?: Payment;
}
