import { Cart } from './cart/cart';
import { Follows } from './follow/follow';
import { Inquiry, SupportRecipient } from './inquiry/inquiry';
import { Comment, Comments } from './comment/comment';
import { AuthPayload, Member, Members } from './member/member';
import { Order, Orders } from './order/order';
import { Notification, Notifications } from './notification/notification';
import { Payment } from './payment/payment';
import { Pet, Pets } from './pet/pet';
import { Product, Products } from './product/product';

export interface T {
	getSupportRecipients?: SupportRecipient[];
	getMyInquiries?: Inquiry[];
	getAssignedInquiries?: Inquiry[];
	createInquiry?: Inquiry;
	answerInquiry?: Inquiry;
	getAllProductsByAdmin?: Products;
	getAllPetsByAdmin?: Pets;
	getAllOrdersByAdmin?: Orders;
	getPaymentByOrderByAdmin?: Payment | null;
	confirmPayment?: Payment;
	getAllMembersByAdmin?: { list: Member[]; metaCounter: { total: number }[] };
	getAllCommentsByAdmin?: Comments;
	updateProductByAdmin?: Product;
	updatePetByAdmin?: Pet;
	updateOrderStatusByAdmin?: Order;
	updateMemberByAdmin?: Member;
	removeCommentByAdmin?: Comment;
	signup?: Member;
	login?: AuthPayload;
	getMember?: Member;
	getAgents?: Members;
	getMemberFollowers?: Follows;
	getMemberFollowings?: Follows;
	updateMember?: Member;
	getProduct?: Product;
	getProducts?: Products;
	getFavoriteProducts?: Products;
	getVisitedProducts?: Products;
	getMyProducts?: Products;
	createProduct?: Product;
	updateProduct?: Product;
	removeProduct?: Product;
	likeTargetProduct?: Product;
	getPets?: Pets;
	getPet?: Pet;
	getMyPets?: Pets;
	getFavoritePets?: Pets;
	getVisitedPets?: Pets;
	getComments?: Comments;
	createComment?: Comment;
	updateComment?: Comment;
	likeTargetPet?: Pet;
	createPet?: Pet;
	updatePet?: Pet;
	getMyCart?: Cart;
	addToCart?: Cart;
	updateCartItem?: Cart;
	removeCartItem?: Cart;
	clearCart?: Cart;
	createOrder?: Order;
	getMyOrders?: Orders;
	getMyNotifications?: Notifications;
	readNotification?: Notification;
	getOrder?: Order;
	cancelOrder?: Order;
	createPayment?: Payment;
}
